#!/usr/bin/with-contenv bash

export HOME=/home/steam

#echo "Updating Mordhao Server..."
#exec s6-setuidgid steam /home/steam/steamcmd/steamcmd.sh +runscript /home/steam/update_mordhao.txt

echo "Starting Mordhao Server..."
exec s6-setuidgid steam \
    /mnt/steam/mordhau/MordhauServer.sh \
    -Port=7777 \
    -QueryPort=27015 \
    -Beaconport=15000 \
    -GAMEINI=/home/steam/mordhao.ini \
;
