#!/usr/bin/with-contenv bash

set -eu

export HOME=/home/steam

cd "$HOME"

GAME_INI="${GAME_INI:-/etc/mordhau/Game.ini}"
[ -e "$GAME_INI" ]

ENGINE_INI="${ENGINE_INI:-/etc/mordhau/Engine.ini}"
[ -e "$ENGINE_INI" ]

# copy the game ini so that we can replace passwords
# tmp should be a tmpfs so this won't touch disk
# when the server starts, it also writes a bunch of settings out to the ini. we could disable that, but its nice to see what is running
cp "$GAME_INI" /tmp/Game.ini
cp "$ENGINE_INI" /tmp/Engine.ini

GAME_INI=/tmp/Game.ini
ENGINE_INI=/tmp/Engine.ini

chmod 600 "$GAME_INI"
chmod 600 "$ENGINE_INI"

chown steam:steam "$GAME_INI"
chown steam:steam "$ENGINE_INI"

# everything else is safe to include in a config on disk
sed -i 's/${SERVER_PASSWORD}/'"${SERVER_PASSWORD:-}"'/' "$GAME_INI"
sed -i 's/${ADMIN_PASSWORD}/'"${ADMIN_PASSWORD:-}"'/' "$GAME_INI"

# print the config (but without printing any passwords)
echo
echo "GAME_INI: $GAME_INI"
echo
grep -v "Password=" "$GAME_INI"

echo
echo "ENGINE_INI: $ENGINE_INI"
echo
cat "$ENGINE_INI"

cmd_array=(
    MordhauServer.sh
    "-Port=${PORT:-7777}"
    "-QueryPort=${QUERY_PORT:-27015}"
    "-BeaconPort=${BEACON_PORT:-15000}"
    "-GAMEINI=$GAME_INI"
    "-ENGINEINI=$ENGINE_INI"
)

if [ -n "${MULTIHOME}" ]; then
    cmd_array+=(
        "-multihome=$MULTIHOME"
    )
fi

echo "Starting Mordhau Server..."
set -x
exec s6-setuidgid steam "${cmd_array[@]}"
