#!/usr/bin/with-contenv sh

set -e

export HOME=/home/steam

cd "$HOME"

s6-setuidgid steam mkdir -p Steam steamcmd

# docker volumes sometimes break ownership
# i was using fix-attrs.d, but we only care about changing ownership
if [ "$(stat -c '%U' Steam)" != "steam" ]; then
    chown -R steam:steam Steam &
fi
if [ "$(stat -c '%U' steamcmd)" != "steam" ]; then
    chown -R steam:steam steamcmd &
fi
wait

if [ -e "steamcmd/steamcmd.sh" ]; then
    # TODO: check if modified date matches /opt/steamcmd and upgrade if not
    :
else
    # TODO: rsync? 
    # copy from /opt/ since it stores a bunch of packages and caches next to it and we want a docker volume to save those
    s6-setuidgid steam cp -r /opt/steamcmd/* steamcmd/
fi

# $HOME/steamcmd is already on the path

# TODO: option to run validate_mordhau.txt instead

s6-setuidgid steam \
    steamcmd.sh +runscript /etc/mordhau/validate_mordhau.txt
